Run

diff --git a/python-hello_world/0-run b/python-hello_world/0-run
--- a/python-hello_world/0-run
+++ b/python-hello_world/0-run
@@ -1,11 +1,4 @@
 #!/bin/bash
 
-# Check if PYFILE environment variable is set
-if [ -z "$PYFILE" ]; then
-    echo "Error: PYFILE environment variable is not set."
-    exit 1
-fi
-
-# If PYFILE is set, execute the Python script
-python3 "$PYFILE"
+[ -z "$PYFILE" ] && { echo "Error: PYFILE environment variable is not set."; exit 1; }; python3 "$PYFILE"
 
